config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "callbacks"}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :challenges, only: %i[show index new create destroy edit update] do
    resources :offers, only: %i[show index create update]
    resources :comments, only: %i[index create]
  end
  resources :users, only: [:index, :show, :edit, :update], path: "index" do
  end
  resources :offers, only: %i[destroy]
  # resources :comments, only: %i[edit update destroy]
  get '/my_challenges', action: :index, controller: 'challenges'
  get '/my_offers', action: :index, controller: 'offers'
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <div class="container second">
      <h1 class="display-4 justify-content-center">DEV.WORK</h1>
      <p class="justify-content-center"> Find solutions to your challenges!</p>
      <%= link_to "Learn More", challenges_path, class:"btn btn-primary btn-lg mt-6 learn_more" %>
    </div>
  </div>
</div>

app/views/shared/_button.html.erb
<a href="#" class="btn btn-dark btn-lg rounded-lg" id="button" role="button">Primary link</a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" id="offer-alert" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer border-top">
  <footer class="py-2 text-center text-lg-start">
    <section>
      <div class="container text-center text-md-start ">
        <div class="row mt-3">
          <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase mb-4">
            <i class="fas fa-gem me-3"></i>Dev.Work
          </h6>
          <p>
            Find developers to work with and solve complex challenges together!
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase mb-4">
            Dev language
          </h6>
          <p>
            <%= link_to "Ruby on rails", "#", class: "text-reset"%>
          </p>
          <p>
            <%= link_to "JavaScript", "#", class: "text-reset"%>
          </p>
          <p>
            <%= link_to "Python", "#", class: "text-reset"%>
          </p>
          <p>
            <%= link_to "View more", "#", class: "text-reset"%>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase mb-4">
            Useful links
          </h6>
          <p>
            <a href="#" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#" class="text-reset">Account info</a>
          </p>
          <p>
            <a href="#" class="text-reset">Your orders</a>
          </p>
          <p>
            <a href="#" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase mb-4">Contact us</h6>
          <p><i class="fa-solid fa-map me-3"></i></i>Rue de Vermont 1209, Geneva</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            <%= link_to  "devworks@gmail.com", "#"  %>
          </p>
          <p><i class="fas fa-phone me-3"></i> + 41 234 567 88</p>
        </div>
        <!-- Grid column -->
      </div>
      </div>
    </section>

    <section class="p-4 border-top">
      <div class="me-3 d-none d-lg-block text-center mb-2">
        <span>Connect with us: </span>
      </div>
      <div class="links d-flex justify-content-center ">
        <%= link_to "https://www.twitter.com", target:"_blank" do   %>
          <%= fa_stacked_icon "twitter", base: "square-o", class: "me-4" %>
        <% end %>
        <%= link_to "https://www.facebook.com", target:"_blank" do   %>
          <%= fa_stacked_icon "facebook", base: "square-o", class: "me-4" %>
        <% end %>
        <%= link_to "https://www.github.com", target:"_blank" do   %>
          <%= fa_stacked_icon "github", base: "square-o", class: "me-4" %>
        <% end %>
        <%= link_to "https://www.instagram.com", target:"_blank" do   %>
          <%= fa_stacked_icon "instagram", base: "square-o", class: "me-4" %>
        <% end %>
      </div>
    </section>
  </footer>
</div>

app/views/shared/_index-cards.html.erb
<div class="container mt-5 mb-3 cards">
  <div class="grid">
    <% @challenges.each_with_index do |challenge, index| %>
      <%# <div class="col-md-4"> %>
        <div class="flex flex-column justify-content-between card p-3 mb-2 card-bg">
          <div>
            <div class="d-flex justify-content-between border-bottom pb-3">
              <div class="d-flex flex-row align-items-center ">
                <div class="image">
                   <% if challenge.user.image? %>
                    <%= image_tag "#{challenge.user.image}" %>
                  <% elsif challenge.user.photo.attached? %>
                    <%= cl_image_tag(challenge.user.photo.key) %>
                  <% end %>
                </div>
                <%# <div class="ms-2 c-details">
                   <span>1 days ago</span>
              </div> %>
                <div class="ms-2 c-details">
                  <h5 style="opacity:0">.</h5>
                  <h5 style="justify-content: space-between; align-items: right;"><%= challenge.user.name %>
                  </h5>
                  <h6><i class="fa-sharp fa-solid fa-location-dot fa-xl"></i> <%= challenge.location %></h6>
                </div>

              </div>
              <div class="badge"><%= challenge.filter.name %>
              </div>

            </div>
            <div class="mb-5 mt-3">
              <h2 class="heading"><%= challenge.title %>
              </h2>
            </div>
            <div class="my-3">
                <div class="my-3"> <span class="text1">Deadline: <span class="text2"><%= challenge.deadline.strftime("%B %d, %Y") %>
                </span>
                </span>
                </div>
             </div>
          </div>
          <%= link_to "View details", challenge_path(challenge), class:"btn btn-dark btn-lg rounded-lg", id:"button"%>
        </div>
      <%# </div> %>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar" data-controller="sidebar" data-sidebar-target="sidebar">
  <div class="logo-details">
    <%# <i class='fa-solid fa-laptop-code icon'></i> %>
    <% if user_signed_in? %>
      <div class="logo_name">Hello,
      <br>
      <%= "#{current_user.nickname}"%>!
      </div>
      <i class='bx bx-menu' id="btn" data-sidebar-target="menu" data-action="click->sidebar#change"></i>
    <% end %>
  </div>
  <div class="div">
    <% if user_signed_in? %>
      <% if current_user.image? %>
        <%= image_tag "#{current_user.image}", class: "avatar-custom2" %>
      <% else %>
        <%= cl_image_tag current_user.image.key, height: 200, width: 200, class: "avatar-custom2" %>
      <% end %>
    <% end %>
  </div>
  <ul class="nav-list" style="padding-left:0rem">
    <li>
      <div>
      <i class='bx bx-search' data-sidebar-target="search" data-action="click->sidebar#change"></i>
        <%= form_with url: challenges_path, method: :get, class: "d-flex" do  %>
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a challenge", autocomplete: "off" %>
        <% end %>
      </div>
    </li>
    <%# <li> %>
      <%#= link_to "/profile" do %>
        <%# <i class="fa-regular fa-address-card"></i>
        <span class="links_name">Edit Profile</span> %>
      <%# end %>
        <%# <span class="tooltip">Edit Profile</span> %>
    <%# </li> %>
    <li>
      <%= link_to "/challenges" do %>
        <i class='bx bx-grid-alt'></i>
        <span class="links_name">Challenges</span>
      <% end %>
        <span class="tooltip">Challenges</span>
    </li>
    <li>
      <%= link_to "/my_challenges" do %>
        <i class='bx bx-code-block' ></i>
        <span class="links_name">My Challenges</span>
      <% end %>
      <span class="tooltip">My Challenges</span>
    </li>
    <li>
      <%= link_to "/challenges/new" do %>
        <i class='bx bx-plus-circle' ></i>
        <span class="links_name">New Challenge</span>
      <% end %>
      <span class="tooltip">New Challenge</span>
    </li>
    <li>
      <%= link_to "/my_offers" do %>
        <i class='bx bx-spreadsheet' ></i>
        <span class="links_name">My Offers</span>
      <% end %>
      <span class="tooltip">My Offers</span>
    </li>
    <li>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "nav-link" do %>
          <i class="fa-solid fa-right-to-bracket"></i>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>