config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "callbacks"}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :challenges, only: %i[show index new create destroy edit update] do
    resources :offers, only: %i[show index create update]
    resources :comments, only: %i[index create]
  end
  resources :users, only: [:index, :show, :edit, :update], path: "index" do
  end
  resources :offers, only: %i[destroy]
  # resources :comments, only: %i[edit update destroy]
  get '/my_challenges', action: :index, controller: 'challenges'
  get '/my_offers', action: :index, controller: 'offers'
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :filter
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :photos

  validates :title, :content, :price_max, :deadline, :location, presence: true

  geocoded_by :location

  after_validation :geocode, if: :location
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  include ActionView::Helpers::UrlHelper

  before_action :set_challenge, only: %i[show edit update destroy]

  def show
    authorize @challenge
    @offers = @challenge.offers
    @offer = Offer.new
  end

  def index
    @challenges = policy_scope(Challenge)
    @filters = Filter.all
    if params[:filter].present? && params[:query].present? && params[:location].present?
      @filter = Filter.find_by(name: params[:filter])
      @challenges = Challenge.where('filter_id = ?', @filter.id).where("title ILIKE ?", "%#{params[:query]}%").where(location: params[:location])
    elsif params[:query].present? && params[:location].present?
      @challenges = Challenge.where("title ILIKE ?", "%#{params[:query]}%").where(location: params[:location])
    elsif params[:filter].present? && params[:location].present?
      @filter = Filter.find_by(name: params[:filter])
      @challenges = Challenge.where('filter_id = ?', @filter.id).where(location: params[:location])
    elsif params[:filter].present? && params[:query].present?
      @filter = Filter.find_by(name: params[:filter])
      @challenges = Challenge.where('filter_id = ?', @filter.id).where("title ILIKE ?", "%#{params[:query]}%")
    elsif params[:query].present?
      @challenges = Challenge.where("title ILIKE ?", "%#{params[:query]}%")
    elsif params[:location].present?
      @challenges = Challenge.where(location: params[:location])
    elsif params[:filter].present?
      @filter = Filter.find_by(name: params[:filter])
      @challenges = Challenge.where('filter_id = ?', @filter.id)
    elsif current_page?(my_challenges_path)
      @challenges = current_user.challenges
    else
      @challenges = Challenge.all
    end

    locations = Challenge.distinct.pluck(:location)
    @location_filters = []
    locations.each do |location|
      if !location.nil?
        @location_filters << location
      end
    end

    @markers = @challenges.geocoded.map do |challenge|
      {
        lat: challenge.latitude,
        lng: challenge.longitude,
        info_window: render_to_string(partial: "info_window", locals: {challenge: challenge})
      }
    end
  end

  def new
    @challenge = Challenge.new
    authorize @challenge
  end

  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.user = current_user
    @challenge.filter = Filter.find(params[:challenge][:filter_id])
    authorize @challenge
    if @challenge.save
      redirect_to challenge_path(@challenge)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @challenge
    @challenge.destroy
    redirect_to challenges_path(@challenges), status: :see_other
  end

  def edit
    authorize @challenge
  end

  def update
    authorize @challenge
    @challenge.update(challenge_params)
    redirect_to challenge_path(@challenge)
  end

  private

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:title, :content, :price_max, :deadline, :location, photos: [])
  end
end

app/views/challenges/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/challenges/_info_window.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="map-profile">
      <div class="d-flex flex-row justify-content-between align-items-center">
        <div style="margin-right:30px">
          <% if challenge.user.image %>
            <%= image_tag challenge.user.image, class: "avatar-custom", style:"height:80px !important; width:80px !important" %>
          <% elsif challenge.user.photo %>
            <%= cl_image_tag challenge.user.photo.key, class: "avatar-custom", style:"height:80px !important; width:80px !important" %>
          <% else %>
            <%= image_tag "userphoto_square.jpg", class:"avatar-custom", style: "height:80px; width:67.8px" %>
          <% end %>
        </div>
      <div class="d-flex flex-row justify-content-between">

        <div class="d-flex flex-column justify-content-center align-items-center">
          <h5 style="color:#555B6E"><%= challenge.user.nickname %>: <%= challenge.title %></h5>
          <div class="d-flex align-items-center">
          <% if !challenge.user.html_url.nil? %>
            <%= link_to "GitHub", challenge.user.html_url, class:"btn rounded-5 btn-sm", style:"background-color:#8d7197; color:white" %>
          <% else %>
            <%= link_to "GitHub", "https://www.github.com", class:"btn rounded-5 btn-sm", style:"background-color:#8d7197; color:white" %>
          <% end %>
          <%= link_to "Challenge", challenge_path(challenge), class:"btn rounded-5 btn-sm", style:"background-color:#8d7197; color:white" %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/challenges/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow" style="border-radius:15px !important;">
        <h3>Update challenge</h3>
        <%= simple_form_for @challenge do |f| %>
          <%= f.input :title, placeholder: 'Edit the Title' %>
          <%= f.input :content, placeholder: 'Edit the description' %>
          <%= f.input :location, placeholder: 'Edit Challenge location' %>
          <%= f.association :filter, label: "Programming language ¹", collection: Filter.all.order(:name), input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :price_max, placeholder: 'Edit price of your project' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :deadline, placeholder: 'Edit deadline of your project' %>
          <%= f.submit class:"btn btn-dark btn-lg rounded-lg", id: "challenge_buttons" %>
        <% end %>
      </div>
      <div class="div" style="height:10px"></div>
      <div class="bg-white rounded p-3 shadow" style="border-radius:15px !important; text-align:left !important; opacity:0.9 !important">
        <p style="font-weight: 200 !important">* All the fields need to be present for successful update</p>
        <p style="font-weight: 200 !important"><sup>1</sup> You cannot change the programming language of the challenge - for that you need to create a new one</p>
      </div>
    </div>
  </div>
</div>

app/views/challenges/index.html.erb
<div class="my-3">
  <% if current_page?(challenges_path) %>
    <div class="container header text-center index-image">
      <div class="container" id="title">
        <h1 class="pt-2">Welcome to Dev.Work</h1>
        <p class="pb-2">Find challenges below and help out fellow developers</p>
      </div>
    </div>
    <div class="container">
      <div data-controller="map"
        id="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value=" <%= @markers.to_json %>"
        style='width: 100%px; height:500px;'>
      </div>
    </div>
    <div class="index-event-card text-center sidead" style="width: 250px;" >
      <h3 style="font-size: large">Are you always working and <u>cannot socialize</u>?</h3>
      <%= image_tag "ad-1 (1).jpg", class:'my-2', style:'width:200px' %>
      <h3 style="font-size: large">You have tried making friends but <u>no coders around you</u>?</h3>
      <%= image_tag "ad-1 (2).jpg", class:'my-2', style:'width:200px' %>
      <h3 style="font-size: large">Are you looking for a <u>place to socialize</u> and <u>talk about coding</u>?</h3>
      <%= image_tag "ad-1 (3).jpg", class:'my-2', style:'width:200px' %>
      <h3 style="font-size: xx-large">Check out <a href="https://www.socialize.tech" class="adlink" style="text-decoration:none !important, color:#555B6E !important">Socialize!</a></h3>
      <%= image_tag "Socialize.png", style:'width:130px' %>
    </div>
      <div class="d-flex justify-content-center">
        <div class="div">
          <div class="container pt-1 bg-white" id="filtertext">
            <% if @filter.present? %>
              <p style="margin-top: 3px !important;"><%= "Your have selected #{@filter.name} language" %></p>
            <% elsif params[:location].present? %>
              <p style="margin-top: 3px !important;"><%= "Your have selected #{params[:location]} city" %></p>
            <% else %>
              <p style="margin-top: 3px !important;"><%= "Your have not selected any filter" %></p>
            <% end %>
          </div>
        </div>
        <div class="spacerr" style="width:50px"></div>
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="filterbutton">
            Filter the languages
          </button>
          <ul class="dropdown-menu">
            <% @filters.each do |filter| %>
              <li><%= link_to filter.name, challenges_path(filter: filter.name), class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
        <div class="spacerr" style="width:50px"></div>
        <div class="dropdown d-flex justify-content-end">
          <button class="btn btn-primary dropdown-toggle rounded-4" type="button" data-bs-toggle="dropdown" aria-expanded="false" >
            Filter the cities
          </button>
          <ul class="dropdown-menu">
            <% @location_filters.sort.each do |location| %>
              <li><%= link_to location, challenges_path(location: location), class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </div>
        <div class="spacerr" style="width:50px"></div>
        <%= link_to "Reset filters", challenges_path, class:"btn btn-secondary", id:"resetfilterbutton"%>
      </div>
      <%= render "shared/index-cards" %>
  <% end %>
  <% if current_page?(my_challenges_path) %>
    <div class="container header text-center index-image">
      <div class="container" id="title">
        <h1 class="pt-2">Your Challenges</h1>
        <% if @challenges.empty? %>
          <p>You have not posted a challenge yet! Check back again later...</p>
        <% else %>
          <p class="pb-2">Below you can see all the challenges you have created</p>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div data-controller="map"
        id="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value=" <%= @markers.to_json %>"
        style='width: 100%px; height:500px;'>
      </div>
    </div>
    <%= render "shared/index-cards" %>
  <% end %>
</div>

app/views/challenges/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white p-3 shadow" style="border-radius:15px !important;">
        <h3>Create a new challenge</h3>
        <%= simple_form_for @challenge do |f| %>
          <%= f.input :title, placeholder: 'Add a Title' %>
          <%= f.input :content, placeholder: 'Describe in Details' %>
          <%= f.input :location, placeholder: 'Specify Challenge location' %>
          <%= f.association :filter, label: "Programming language ¹", collection: Filter.all.order(:name), input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :price_max, placeholder: 'Put maximum price in Euros' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :deadline, placeholder: 'Put a deadline for your project' %>
          <%= f.submit class:"btn btn-dark btn-lg rounded-lg challenge-buttons", id: "challenge_buttons" %>
        <% end %>
      </div>
      <div class="div" style="height:10px"></div>
      <div class="bg-white rounded p-3 shadow" style="border-radius:15px !important; text-align:left !important; opacity:0.9 !important">
        <p style="font-weight: 200 !important">* All the fields need to be present for successful challenge creation</p>
        <p style="font-weight: 200 !important"><sup>1</sup> You will not be able to change the programming language of the challenge afterwards - choose wisely</p>
      </div>
    </div>
  </div>
</div>

app/views/challenges/show.html.erb
<div class="container">
  <div class="grid show-grid my-4">
    <div class="left">
      <div class="row show">
        <%# ALL: The challenge itself %>
        <div class="cardshow">
          <div class="card-image">
            <% if @challenge.user.image? %>
              <%= image_tag "#{@challenge.user.image}" %>
            <% elsif @challenge.user.photo.attached? %>
              <%= cl_image_tag(@challenge.user.photo.key) %>
            <% end %>
          </div>
          <h6><%= @challenge.user.nickname %></h6>
          <h6><i class="fa-sharp fa-solid fa-location-dot fa-xl"></i> <%= @challenge.location %> </h6>
          <div class="card-body">
            <div>
              <h1><%= @challenge.title %></h1>
              <p><strong>Maximum price: </strong>€<%= @challenge.price_max %></p>
              <p><strong>Deadline: </strong><%= @challenge.deadline.strftime("%B %d, %Y") %></p>
              <p><strong>Language: </strong><%= @challenge.filter.name %></p>
              <p><%= @challenge.content %></p>
              <% @challenge.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 400, width: 600, crop: :fit, class:"my-1" %>
              <% end %>
            </div>
            <% if policy(@challenge).edit? %>
              <%= link_to "Delete this challenge", challenge_path(@challenge), class: "btn btn-danger mt-5 mb-1", id: "challenge_buttons",
                  style:"color:white; background-color:#D0021B !important; border-color:#D0021B !important;",
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure to delete this challenge?" } %>
              <%= link_to "Edit this challenge", edit_challenge_path(@challenge), class: "btn btn-info mt-5 mb-1", id: "challenge_buttons" %>
              <%= link_to "Back to Challenges", "/challenges", class:"btn btn-secondary btn mt-5 mb-1", style:"border-radius:15px" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row show-top-right">
        <%# ONLY USERS: Form for those making an offer %>
        <% if current_user != @challenge.user %>
          <div class="cardshow mt-3">
            <div class="card-body">
              <h2>Offer your skills</h2>
              <p>Do you think you have the required skills? Let them know for how much
                you could do the challenge and how long it will take you:</p>
                <%= simple_form_for [@challenge, @offer] do |f| %>
                <div class="row d-flex flex-row justify-content-around">
                  <div class="col-3">
                    <%= f.input :price, label: "Price, €" %>
                  </div>
                  <div class="col-8">
                    <%= f.input :date, label: 'Proposed date of completion' %>
                  </div>
                </div>
                <div class="d-flex justify-content-around">
                  <%= f.submit "Make offer", class:"btn btn-dark btn-lg rounded-lg mt-2", id:"button" %>
                  <% end %>
                  <%= link_to "Back to Challenges", "/challenges", class:"btn btn-secondary btn-lg mt-2", style:"border-radius:15px" %>
                  </div>
            </div>
          </div>
        <% end %>

        <%# ONLY OWNERS: Showing the offers made and able to accept offer %>
        <% if current_user == @challenge.user %>
          <div class="cardshow mt-3">
            <div class="card-body">
              <h2>Offers</h2>
              <% if @offers.empty? %>
                <p>There are no offers on this challenge! Check back again later...</p>
              <% else %>
                <div>
                  <ul class="px-0 offers">
                    <%# <div class="container mt-5 mb-3 cards"> %>
                        <% @offers.each do |offer| %>
                        <div class="grid_offer">


                              <div class="d-flex flex-column justify-content-between card p-3 mb-2 card-bg" style="hegiht:350px !important; width:350px !important">
                                  <%# <div class="d-flex justify-content-between pb-3"> %>
                                    <div class="d-flex flex-row ">
                                      <div class="image">
                                        <% if offer.user.image.present? %>
                                          <%= image_tag(offer.user.image, class: "avatar-offer") %>
                                        <% elsif @offer.user.photo.attached? %>
                                          <%= cl_image_tag(@offer.user.photo.key) %>
                                        <% end %>
                                      </div>
                                      <div style="width:20px; height:20px"></div>
                                      <div class="d-flex flex-column">
                                        <div class="ms-2 c-details">
                                          <p style="font-size:30px"><%= offer.user.nickname %>
                                          </p>
                                        </div>
                                        <%#= image_tag(offer.user.image, class: "avatar-offer") %>
                                        <p>Offered price: €<%= offer.price %></p>
                                      </div>
                                    </div>
                                        <p class="my-3">Offered date of completion: <%= offer.date %></p>
                                  <%= link_to "Accept offer", challenge_path(@challenge), class: "btn btn-success", id: "challenge_buttons", style:"background-color:#009900; color:#ffffff; border-width:0px" %>
                                </div>
                              </div>

                        <% end %>
                    </ul>
                  </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%# ALL: Comments left on the challenge %>
    <div class="cardshow p-4">
      <div class="card-body-1">
        <h2>Comments</h2>
        <% if @comments.nil? %>
          <p>There are no comments on this challenge! Check back again later...</p>
        <% else %>
          <div class="comments px-0">
            <% @comments.each do |comment| %>
              <div class="comment py-3">
                <%= cl_image_tag(comment.user.photo.key, class: "avatar") %>
                <%= comment %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>